languageKey:
  name: languageKey
  in: path
  required: true
  type: string
  example: de

newUserOrLogin:
  name: User
  in: body
  description: New user to create
  required: true
  schema:
    $ref: '#/definitions/NewUserOrLogin'

domainId:
  name: domainId
  in: path
  description: The ID of a Domain.
  required: true
  type: string
newDomain:
  name: Domain
  in: body
  description: New domain to create
  required: true
  schema:
    $ref: '#/definitions/NewDomain'
newScenario:
  name: Scenario
  in: body
  description: New scenario to create
  required: true
  schema:
    $ref: '#/definitions/NewScenario'
newNode:
  name: Node
  in: body
  description: New node to create
  required: true
  schema:
    $ref: '#/definitions/NewNode'

updateNode:
  name: Node
  in: body
  description: Updated fields of node to apply
  required: true
  schema:
    $ref: '#/definitions/UpdateNode'

scenarioId:
  name: scenarioId
  in: path
  description: The ID of a scenario
  required: true
  type: string
nodeId:
  name: nodeId
  in: path
  description: The ID of a node
  required: true
  type: string
machineId:
  name: machineId
  in: path
  description: The ID of a machine.
  required: true
  type: string
processsheetId:
  name: processsheetId
  in: path
  description: The ID of a processsheet.
  required: true
  type: string
machine:
  name: machine
  in: body
  description: Machine to add.
  required: true
  schema:
    $ref: '#/definitions/NewMachine'
machineState:
  name: machineState
  in: body
  description: Machine state.
  required: true
  schema:
    $ref: '#/definitions/MachineState'

  
definitions:
  $ref: ./definitions.yaml